### PR TITLE
Master cf resync

### PR DESCRIPTION
**Pull request by mingwandroid**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `1` - to align with AD (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Hi @zooba, I've copied some MS MAPI headers so that the exchange stuff can be built. The headers end up in the package's internal copy of the recipe. Is this OK? The previous fix involved disabling some exchange stuff which I'd rather not do. If this is not OK, I'll need to think of something else.

### CODE REVIEW

**Comment by isuruf** [comment]
You can download https://download.microsoft.com/download/B/6/4/B645F2C9-715A-4EAB-B561-CC0C9779C249/Outlook2010MAPIHeaders.EXE at build time and extract the exe to get the headers.

**Comment by mingwandroid** [comment]
Thanks for the hint!

**Comment by isuruf** [comment]
```
wget https://download.microsoft.com/download/B/6/4/B645F2C9-715A-4EAB-B561-CC0C9779C249/Outlook2010MAPIHeaders.EXE
7z e Outlook2010MAPIHeaders.EXE
7z e OUTLOO~1.EXE
```
gives the headers to me on Linux

**Comment by mingwandroid** [comment]
Thanks all. Using powershell to download and bsdtar to extract on Windows.

**Comment by hmaarrfk** [comment]
Any new traction on this?

**Comment by carlodri** [comment]
@conda-forge-admin, please rerender

**Comment by carlodri** [comment]
@mingwandroid @hmaarrfk I have merged #20 with an attempt to fix #18  and bringing in some stuff from this PR. Let me know if there is any improvement.

**Comment by nicoddemus** [comment]
This is pretty old so I think we can close this for now, but feel free to reopen otherwise.

**Pull request closed without merging**
