### PR TITLE
Add noop noarch

### LINKED ISSUE #34: Make a no-op, noarch output to increase downstream noarch-ability?
A lot of packages can't be `noarch: python` solely because of a dependency on this package, sometimes for a single bit of information from the registry, or whatever. I have no data to back it up, but I've got the feeling it's in the hundreds. What if there was a no-op `output` for other platforms?

## Prior art
- similar tricks have been played for other python feedstocks, so that downstreams can be `noarch: python` e.g. 
  - https://github.com/conda-forge/importlib_metadata-feedstock/blob/master/recipe/meta.yaml
  - https://github.com/conda-forge/dataclasses-feedstock/blob/master/recipe/meta.yaml

## Pro
- a large number of packages could be made `noarch: python`
- migrations would not have to consider them
- historic branches would often no longer need ABI backports

## Con
- definitely be an abuse of the conda system
- fewer release would be built, sometimes 1/10th
- a lot of releases are only ever built upstream on unix-like systems
  - while it's good and helpful for conda-forge to be upstreaming packaging PRs... it's exhausting
- a lot of packages wouldn't be tested on windows

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
  * > ... _and how!_ 
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
  * > a little  surprised about all the extra excursions, was just expecting 1 :woman_shrugging: 
* [x] Ensured the license file is being packaged.

- fixes #34
- tried the https://github.com/conda-forge/staged-recipes/pull/13833#issuecomment-770281289 but don't think it can be neatly solved from the outside

### CODE REVIEW

**Comment by bollwyvl** [comment]
Well, @conda-forge/pywin32, it's terrible, but it appears to work.

**Comment by carlodri** [comment]
@bollwyvl thanks for the PR! Honestly I don't have the time and the conda-forge knowledge to assess if this blows something up. Others @conda-forge/pywin32 please chime in... 🙏 

@isuruf you seemed to suggest that this is ok in #34, can you confirm?

**Comment by bollwyvl** [comment]
Here's another approach at this:

**Comment by bollwyvl** [comment]
An alternate approach is now available from:

https://github.com/conda-forge/pywin32-on-windows-feedstock

**Pull request closed without merging**
