### PR TITLE
Update and Python 3.9

### PR DESCRIPTION
**Pull request by chrisburr**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Closes #26
Closes #28

### CODE REVIEW

**Comment by chrisburr** [comment]
@conda-forge-admin, please restart ci

**Comment by chrisburr** [comment]
@conda-forge-admin, please restart ci

**Comment by chrisburr** [comment]
I'm out of time for now but I think Python 3.9 broken by: https://github.com/python/cpython/commit/0d30ae1a03102de07758650af9243fd31211325a

**Comment by chrisburr** [comment]
@conda-forge/pywin32 This is ready but note there is an ugly hack (f7719cf + bd6496b) to avoid mhammond/pywin32#590 (which is caused by [bpo-42009](https://bugs.python.org/issue42009)).

**Comment by mariusvniekerk** [comment]
Wow thats ugly, but i guess it works for now

**Comment by chrisburr** [comment]
It's a lot better than my first attempt... 😆 https://github.com/conda-forge/pywin32-feedstock/pull/29/commits/85de9d1b9ca638200973856529d4ccb9b912e8ea#diff-e178b687b10a71a3348107ae3154e44c

It might be possible to run message compiler manually to generate the those two header files but I'm not sure how.

**Comment by carlodri** [comment]
thanks a lot @chrisburr for looking into this!

**Pull request merged**
